### ISSUE TITLE
TypeError line 386

### ISSUE THREAD

**Issue by dreidpath** [eliranwong/ChatGPT-GUI#12]
I installed and ran ChatGPT-GUI on a Linux machine:

(venv) $:~/ChatGPT-GUI$ python3 ChatGPT-GUI.py
Traceback (most recent call last):
  File "/ChatGPT-GUI/ChatGPT-GUI.py", line 1078, in <module>
    showMainWindow()
  File "/ChatGPT-GUI/ChatGPT-GUI.py", line 1049, in showMainWindow
    config.mainWindow = MainWindow()
  File "/ChatGPT-GUI/ChatGPT-GUI.py", line 899, in __init__
    self.initUI()
  File "/ChatGPT-GUI/ChatGPT-GUI.py", line 903, in initUI
    self.chatGPT = ChatGPTAPI(self)
  File "/ChatGPT-GUI/ChatGPT-GUI.py", line 249, in __init__
    self.setupUI()
  File "/ChatGPT-GUI/ChatGPT-GUI.py", line 386, in setupUI
    self.temperature.setCurrentIndex(config.chatGPTApiTemperature * 10)
TypeError: setCurrentIndex(self, index: int): argument 1 has unexpected type 'float'

I edited line 386:
self.temperature.setCurrentIndex(int(config.chatGPTApiTemperature * 10))

It seems to be working now.

Thanks

**Comment by eliranwong** [comment]
thanks for reporting the error.

I made the change in https://github.com/eliranwong/ChatGPT-GUI/commit/2d915050ba3862f7d5efbf77d3e4e1680abe8009, as you suggested.
